### ISSUE TITLE
Just a typo

### ISSUE THREAD

**Issue by alexmicouleau** [kbytesys/django-recaptcha3#1]
Hi on your main page/Readme it says

from snowpenguin.django.recaptcha2.fields import ReCaptchaField

when it should say
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

otherwise this seems to work nicely so thanks.

On another matter : Any idea how to force robot detection ?

**Comment by kbytesys** [comment]
Thanks for reporting, I will fix the typo soon!

About the robot detection: we are not in control (at least in the actual release of reCaptcha3) :(
