### ISSUE TITLE
Release latest on PYPI

### ISSUE THREAD

**Issue by urlsangel** [kbytesys/django-recaptcha3#13]
Hi - would it be possible for you to update the release on PYPI to match what's on Github?

I could really use the error code/score functionality :-)

Thanks,

Russell.

**Comment by kbytesys** [comment]
Yep, I will update the release version today/tomorrow.

**Comment by urlsangel** [comment]
@kbytesys 

Thanks Andrea!

**Comment by urlsangel** [comment]
@kbytesys 

Hi Andrea, are you still able to do this today?

Thanks,

Russell.

**Comment by kbytesys** [comment]
I'm working on to check why a couple of automatic builds fails. I hope to complete this task in few hours

**Comment by urlsangel** [comment]
That's great, thanks @kbytesys - sorry to chase!

**Comment by kbytesys** [comment]
https://pypi.org/project/django-recaptcha3/0.2.0/
